name = "glasspane"
main = "worker/src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "glasspane.page", custom_domain = true },
  { pattern = "www.glasspane.page", custom_domain = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SCRIPTS"
id = "6d1dc2347ad94179b8f5b455d548c651"
preview_id = "a9870899540f4c99a668e40c93b2cf13"

[observability]
enabled = true
